export const testAccounts: Account[] = [
    {
      id: "account_1",
      availableBalance: 1500.00,
      currentBalance: 2000.00,
      officialName: "Official Savings Account",
      mask: "1234",
      institutionId: "institution_1",
      name: "Savings Account",
      type: "depository",
      subtype: "savings",
      appwriteItemId: "appwrite_1",
      shareableId: "shareable_1",
    },
    {
      id: "account_2",
      availableBalance: 1000.00,
      currentBalance: 1200.00,
      officialName: "Official Checking Account",
      mask: "5678",
      institutionId: "institution_2",
      name: "Checking Account",
      type: "depository",
      subtype: "checking",
      appwriteItemId: "appwrite_2",
      shareableId: "shareable_2",
    },
    {
      id: "account_3",
      availableBalance: 500.00,
      currentBalance: 700.00,
      officialName: "Official Business Account",
      mask: "9101",
      institutionId: "institution_3",
      name: "Business Account",
      type: "depository",
      subtype: "business",
      appwriteItemId: "appwrite_3",
      shareableId: "shareable_3",
    },
    {
      id: "account_4",
      availableBalance: 2000.00,
      currentBalance: 2500.00,
      officialName: "Official Student Account",
      mask: "1121",
      institutionId: "institution_4",
      name: "Student Account",
      type: "depository",
      subtype: "student",
      appwriteItemId: "appwrite_4",
      shareableId: "shareable_4",
    }
  ];
export const testTransactions: Transaction[] = [
    {
      id: "transaction_1",
      $id: "transaction_1",
      name: "Grocery Store",
      paymentChannel: "in-store",
      type: "debit",
      accountId: "account_1",
      amount: 50.00,
      pending: false,
      category: "Groceries",
      date: "2023-06-01T00:00:00Z",
      image: "image_url_1",
      $createdAt: "2023-06-01T00:00:00Z",
      channel: "in-store",
      senderBankId: "bank_1",
      receiverBankId: "bank_2",
    },
    {
      id: "transaction_2",
      $id: "transaction_2",
      name: "Salary",
      paymentChannel: "direct deposit",
      type: "credit",
      accountId: "account_2",
      amount: 2000.00,
      pending: false,
      category: "Income",
      date: "2023-06-02T00:00:00Z",
      image: "image_url_2",
      $createdAt: "2023-06-02T00:00:00Z",
      channel: "direct deposit",
      senderBankId: "bank_3",
      receiverBankId: "bank_1",
    },
    {
      id: "transaction_3",
      $id: "transaction_3",
      name: "Online Purchase",
      paymentChannel: "online",
      type: "debit",
      accountId: "account_3",
      amount: 150.00,
      pending: true,
      category: "Shopping",
      date: "2023-06-03T00:00:00Z",
      image: "image_url_3",
      $createdAt: "2023-06-03T00:00:00Z",
      channel: "online",
      senderBankId: "bank_1",
      receiverBankId: "bank_4",
    },
    {
      id: "transaction_4",
      $id: "transaction_4",
      name: "Utility Bill",
      paymentChannel: "bank transfer",
      type: "debit",
      accountId: "account_4",
      amount: 100.00,
      pending: false,
      category: "Bills",
      date: "2023-06-04T00:00:00Z",
      image: "image_url_4",
      $createdAt: "2023-06-04T00:00:00Z",
      channel: "bank transfer",
      senderBankId: "bank_2",
      receiverBankId: "bank_3",
    },
    {
      id: "transaction_1",
      $id: "transaction_1",
      name: "Grocery Store",
      paymentChannel: "in-store",
      type: "debit",
      accountId: "account_1",
      amount: 50.00,
      pending: false,
      category: "Groceries",
      date: "2023-06-01T00:00:00Z",
      image: "image_url_1",
      $createdAt: "2023-06-01T00:00:00Z",
      channel: "in-store",
      senderBankId: "bank_1",
      receiverBankId: "bank_2",
    },
    {
      id: "transaction_2",
      $id: "transaction_2",
      name: "Salary",
      paymentChannel: "direct deposit",
      type: "credit",
      accountId: "account_2",
      amount: 2000.00,
      pending: false,
      category: "Income",
      date: "2023-06-02T00:00:00Z",
      image: "image_url_2",
      $createdAt: "2023-06-02T00:00:00Z",
      channel: "direct deposit",
      senderBankId: "bank_3",
      receiverBankId: "bank_1",
    },
    {
      id: "transaction_3",
      $id: "transaction_3",
      name: "Online Purchase",
      paymentChannel: "online",
      type: "debit",
      accountId: "account_3",
      amount: 150.00,
      pending: true,
      category: "Shopping",
      date: "2023-06-03T00:00:00Z",
      image: "image_url_3",
      $createdAt: "2023-06-03T00:00:00Z",
      channel: "online",
      senderBankId: "bank_1",
      receiverBankId: "bank_4",
    },
    {
      id: "transaction_4",
      $id: "transaction_4",
      name: "Utility Bill",
      paymentChannel: "bank transfer",
      type: "debit",
      accountId: "account_4",
      amount: 100.00,
      pending: false,
      category: "Bills",
      date: "2023-06-04T00:00:00Z",
      image: "image_url_4",
      $createdAt: "2023-06-04T00:00:00Z",
      channel: "bank transfer",
      senderBankId: "bank_2",
      receiverBankId: "bank_3",
    },
    {
      id: "transaction_1",
      $id: "transaction_1",
      name: "Grocery Store",
      paymentChannel: "in-store",
      type: "debit",
      accountId: "account_1",
      amount: 50.00,
      pending: false,
      category: "Groceries",
      date: "2023-06-01T00:00:00Z",
      image: "image_url_1",
      $createdAt: "2023-06-01T00:00:00Z",
      channel: "in-store",
      senderBankId: "bank_1",
      receiverBankId: "bank_2",
    },
    {
      id: "transaction_2",
      $id: "transaction_2",
      name: "Salary",
      paymentChannel: "direct deposit",
      type: "credit",
      accountId: "account_2",
      amount: 2000.00,
      pending: false,
      category: "Income",
      date: "2023-06-02T00:00:00Z",
      image: "image_url_2",
      $createdAt: "2023-06-02T00:00:00Z",
      channel: "direct deposit",
      senderBankId: "bank_3",
      receiverBankId: "bank_1",
    },
    {
      id: "transaction_3",
      $id: "transaction_3",
      name: "Online Purchase",
      paymentChannel: "online",
      type: "debit",
      accountId: "account_3",
      amount: 150.00,
      pending: true,
      category: "Shopping",
      date: "2023-06-03T00:00:00Z",
      image: "image_url_3",
      $createdAt: "2023-06-03T00:00:00Z",
      channel: "online",
      senderBankId: "bank_1",
      receiverBankId: "bank_4",
    },
    {
      id: "transaction_4",
      $id: "transaction_4",
      name: "Utility Bill",
      paymentChannel: "bank transfer",
      type: "debit",
      accountId: "account_4",
      amount: 100.00,
      pending: false,
      category: "Bills",
      date: "2023-06-04T00:00:00Z",
      image: "image_url_4",
      $createdAt: "2023-06-04T00:00:00Z",
      channel: "bank transfer",
      senderBankId: "bank_2",
      receiverBankId: "bank_3",
    }
  ];
  
  


  export const testUser: User = {
    $id: "1",
    email: "testuser@example.com",
    userId: "user123",
    dwollaCustomerUrl: "https://api-sandbox.dwolla.com/customers/12345678",
    dwollaCustomerId: "12345678",
    firstName: "John",
    lastName: "Doe",
    name: "John Doe",
    address1: "123 Main St",
    city: "Anytown",
    state: "CA",
    postalCode: "12345",
    dateOfBirth: "1990-01-01",
    ssn: "123-45-6789"
  };
  

  export const banks: (Bank & Account)[] = [
    {
      id: "account123",
      availableBalance: 1500.75,
      currentBalance: 2000.00,
      officialName: "Checking Account",
      mask: "1234",
      institutionId: "bank_abc",
      name: "John's Checking",
      type: "checking",
      subtype: "personal",
      appwriteItemId: "item_123",
      shareableId: "shareable_abc123",
      $id: "bank_123",
      accountId: "account123",
      bankId: "bank_abc",
      accessToken: "access_token_12345",
      fundingSourceUrl: "https://api.example.com/funding-source/12345678",
      userId: "user_123"
    },
    {
      id: "account456",
      availableBalance: 3000.00,
      currentBalance: 3500.00,
      officialName: "Savings Account",
      mask: "5678",
      institutionId: "bank_def",
      name: "Jane's Savings",
      type: "savings",
      subtype: "personal",
      appwriteItemId: "item_456",
      shareableId: "shareable_def456",
      $id: "bank_456",
      accountId: "account456",
      bankId: "bank_def",
      accessToken: "access_token_67890",
      fundingSourceUrl: "https://api.example.com/funding-source/87654321",
      userId: "user_456"
    }
  ];

 export const categories: CategoryCount[] = [
    { name: 'Electronics', count: 10, totalCount: 100 },
    { name: 'Books', count: 5, totalCount: 50 },
    { name: 'Clothing', count: 20, totalCount: 200 },
    { name: 'Home & Kitchen', count: 15, totalCount: 150 },
    { name: 'Sports', count: 7, totalCount: 70 }
  ];